QSuperMacros: QSuperMacrosVersion Class Reference
QSuperMacrosVersion Class Reference
#include <QSuperMacros.h>
Static Public Member Functions
static uint32_t GetMajor ()
static uint32_t GetMinor ()
static uint32_t GetPatch ()
static uint32_t GetTag ()
static QString GetVersion ()
Detailed Description
Get the version of the library
Member Function Documentation
GetMajor()
QSUPER_MACROS_USING_NAMESPACE uint32_t QSuperMacrosVersion::GetMajor () static
Library Major Version
Referenced by GetVersion().
GetMinor()
uint32_t QSuperMacrosVersion::GetMinor () static
Library Minor Version
Referenced by GetVersion().
GetPatch()
uint32_t QSuperMacrosVersion::GetPatch () static
Library Patch Version
GetTag()
uint32_t QSuperMacrosVersion::GetTag () static
Library Tag Version
Referenced by GetVersion().
GetVersion()
QString QSuperMacrosVersion::GetVersion () static
Get version in form major.minor.patch.tag
References GetMajor(), GetMinor(), and GetTag().
The documentation for this class was generated from the following files:
QSuperMacros.h
QSuperMacros.cpp